apiVersion: v1
data:
  mapRoles: |
    - groups: 
      - system:masters 
      rolearn: arn:aws:iam::663320812162:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::663320812162:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1I6TU4OC0ICI9
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-06T15:38:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1824"
  uid: 76533c61-2009-40e6-a404-a6a2bf3295a6
